### ISSUE TITLE
exec is both python keyword and docker command

### ISSUE THREAD

**Issue by kurtbrose** [shopkick/seashore#15]
figure out a clean way to be able to do `executor.docker.exec(...)`

**Comment by mahmoud** [comment]
I recommend trimming off trailing underscores, so it becomes `executor.docker.exec_(...)`. Few to no subcommands will have trailing `-` or `_`.

**Comment by moshez** [comment]
thanks @mahmoud , good solution!

**Comment by kurtbrose** [comment]
I think this one is thoroughly solved.  Maybe we should add a doc though?
